### ISSUE TITLE
Refactor old code

### ISSUE THREAD

**Issue by carstingaxion** [figuren-theater/theater-production-blocks#6]
Parts of rewriting [theatrebase-production-blocks](https://github.com/figuren-theater/deprecated__plugins__v2/tree/main/plugins/theatrebase-production-blocks) to remove internal dependencies and make it just a nice little plugin :rainbow: .

```[tasklist]
### Tasks
- [x] Duration block
- [x] Premiere block
- [x] Targetgroup block
- [x] query-block variations
- [x] Production patterns from https://github.com/figuren-theater/ft-network-block-patterns/tree/main/inc/patterns/__ft_global
- [x] Plugin is translation ready
- [x] translated to de_DE
- [x] translated to de_DE_formal
- [ ] Delete from https://github.com/figuren-theater/deprecated__plugins__v2/tree/main/plugins
- [ ] Delete from https://github.com/figuren-theater/deprecated__Figuren_Theater__v2/blob/master/mu-plugins/Figuren_Theater/src/FeaturesRepo/Feature__produktionen.php
```
