### ISSUE TITLE
Submit to wp.org/plugins

### ISSUE THREAD

**Issue by carstingaxion** [figuren-theater/theater-production-blocks#9]
```[tasklist]
### Tasks
- [ ] Update readme to follow the Standards at https://wordpress.org/plugins/readme.txt
- [ ] Validate readme with https://wpreadme.com/
- [ ] Check that we followed all block guidelines at https://github.com/WordPress/wporg-plugin-guidelines/blob/block-guidelines/blocks.md
- [ ] Validate plugin using the https://wordpress.org/plugins/developers/block-plugin-validator/
- [ ] Run https://wordpress.org/plugins/plugin-check/ without failure
- [ ] Add Banner and Icons
- [ ] Submit for Review
- [ ] Get plugin approved
- [ ] Opt-in for the *community* plugins-taxonomy
- [ ] Opt-in for the *blocks* taxonomy, see https://developer.wordpress.org/plugins/wordpress-org/add-your-plugin-to-the-block-directory/
- [ ] > Go to https://wordpress.org/support/plugin/YOURPLUGIN and look at the sidebar on the right. Click the Subscribe to this Plugin button for email alerts.
```
